### ISSUE TITLE
CMake Error at CMakeLists.txt:3 (project): No CMAKE_CXX_COMPILER could be found.

### ISSUE THREAD

**Issue by guest271314** [spotify/NFDecoder#2]
```
$ cmake .. -GNinja

CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

**Comment by 8W9aG** [comment]
I experienced this issue today on MacOS. I verified that `sudo xcode-select run` was working, and that `xcrun -find c++` was working. Turned out I just needed to `brew upgrade cmake`. Either way this is more of a broader issue unfortunately than one that pertains specifically to this project. Still if you continue to have issues post your system setup here and I will try to help.
